In [3]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [4]:
scalar = tf.constant([[9,2],[8,0]])
scalar
#scalar.ndim

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[9, 2],
       [8, 0]], dtype=int32)>

In [5]:
changeable_tensor = tf.Variable([10,7])
changeable_tensor[0].assign(9)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

In [6]:
random_1 = tf.random.Generator.from_seed(32)
random_1 = random_1.normal(shape=(4,3,2))
random_2 = tf.random.Generator.from_seed(32)
random_2 = random_2.normal(shape=(4,3,2))
print(random_1,random_2, random_1==random_2)
print(tf.random.shuffle(random_1, seed =32))

tf.Tensor(
[[[ 0.7901182   1.585549  ]
  [ 0.4356279   0.23645182]
  [-0.15898712  1.302304  ]]

 [[ 0.959224    0.85874265]
  [-1.518177    1.4020647 ]
  [ 1.5570306  -0.96762174]]

 [[ 0.49529105 -0.648484  ]
  [-1.8700892   2.7830641 ]
  [-0.645002    0.18022095]]

 [[-0.14656258  0.34374258]
  [ 0.41367555  0.175735  ]
  [-1.0871261   0.45905176]]], shape=(4, 3, 2), dtype=float32) tf.Tensor(
[[[ 0.7901182   1.585549  ]
  [ 0.4356279   0.23645182]
  [-0.15898712  1.302304  ]]

 [[ 0.959224    0.85874265]
  [-1.518177    1.4020647 ]
  [ 1.5570306  -0.96762174]]

 [[ 0.49529105 -0.648484  ]
  [-1.8700892   2.7830641 ]
  [-0.645002    0.18022095]]

 [[-0.14656258  0.34374258]
  [ 0.41367555  0.175735  ]
  [-1.0871261   0.45905176]]], shape=(4, 3, 2), dtype=float32) tf.Tensor(
[[[ True  True]
  [ True  True]
  [ True  True]]

 [[ True  True]
  [ True  True]
  [ True  True]]

 [[ True  True]
  [ True  True]
  [ True  True]]

 [[ True  True]
  [ True  True]
  [ True  True]]], shape=(4, 3,

In [7]:
import numpy as np
Numpy_1 = np.arange(1,31)
Tensor_1 = tf.constant(Numpy_1,shape=(1,1,1,1,1,2,1,3,5))
Tensor_2 = tf.constant(Numpy_1)
Tensor_1,Tensor_2

(<tf.Tensor: shape=(1, 1, 1, 1, 1, 2, 1, 3, 5), dtype=int64, numpy=
 array([[[[[[[[[ 1,  2,  3,  4,  5],
               [ 6,  7,  8,  9, 10],
               [11, 12, 13, 14, 15]]],
 
 
             [[[16, 17, 18, 19, 20],
               [21, 22, 23, 24, 25],
               [26, 27, 28, 29, 30]]]]]]]]])>,
 <tf.Tensor: shape=(30,), dtype=int64, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])>)

In [8]:
tensor_3 = tf.ones(shape=(5,4,3,4,6))
tensor_3[:3]

<tf.Tensor: shape=(3, 4, 3, 4, 6), dtype=float32, numpy=
array([[[[[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 

In [9]:
X = tf.constant([[1,2,5,6,7],
                 [3,4,8,9,6]])
Y = tf.constant([[5,6,4,6,8],
                 [7,8,7,2,9]])
#tf.matmul(X,Y)
#tf.matmul(tf.reshape(X,shape=(4,1)),tf.transpose(tf.reshape(Y,shape=(4,1))))
tf.tensordot(X,tf.transpose(Y), axes=([1],[0]))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[129, 133],
       [173, 181]], dtype=int32)>

In [10]:
F = tf.constant([6,5])
E = tf.cast(F, dtype=tf.float16)
E

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([6., 5.], dtype=float16)>

In [11]:
abc = tf.constant(np.random.randint(0,1000,size=100))
abc


<tf.Tensor: shape=(100,), dtype=int64, numpy=
array([649, 743, 176, 269, 191, 340, 984, 871, 839, 670, 583, 525, 137,
       566,  28, 870, 266, 357, 114, 158, 136, 668, 106, 900, 691, 441,
       647, 933, 128, 716, 742, 583, 595, 940, 722,  41, 606, 612, 763,
       951, 893, 599, 950, 890, 922, 361, 474, 439, 728, 808,  46, 828,
       465, 597,  70, 927, 367, 609, 984, 467, 807, 995, 617, 217, 882,
       901, 352, 989, 865, 923,  79, 174, 939, 752, 952, 303, 773, 563,
       357, 711,  22, 837, 881, 313, 470, 669, 187, 999, 659, 174, 238,
       685,  64, 894, 472, 356, 457, 336, 577, 268])>

In [12]:
np.min(abc)
tf.reduce_min(abc)
tf.reduce_max(abc)
tf.reduce_mean(abc)
tf.reduce_sum(abc)
tf.math.reduce_variance(tf.cast(abc, dtype=tf.float32)) # Cast to float32 for variance calculation
tf.math.reduce_std(tf.cast(abc, dtype=tf.float32)) # Cast to float32 for standard deviation calculation

<tf.Tensor: shape=(), dtype=float32, numpy=294.9346923828125>

In [13]:
import tensorflow_probability as tfp
tfp.stats.variance(abc)
tfp.stats.stddev(tf.cast(abc,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=294.9346923828125>

In [14]:
tf.random.set_seed(50)
SQZ_list =tf.constant(tf.random.uniform(shape=(1,6,7,1,1,10,2)))
SQZ = tf.squeeze(SQZ_list,axis =3)
SQZ,SQZ.shape

(<tf.Tensor: shape=(1, 6, 7, 1, 10, 2), dtype=float32, numpy=
 array([[[[[[0.94196117, 0.1697309 ],
            [0.5064962 , 0.27598453],
            [0.899318  , 0.4486513 ],
            [0.43584716, 0.71771336],
            [0.85751176, 0.12559032],
            [0.0875535 , 0.85261035],
            [0.17349517, 0.31913245],
            [0.4845121 , 0.5540675 ],
            [0.6620537 , 0.20845115],
            [0.43225408, 0.9061552 ]]],
 
 
          [[[0.52628434, 0.30039036],
            [0.5774927 , 0.5814352 ],
            [0.7920803 , 0.396855  ],
            [0.02649951, 0.43159127],
            [0.11073196, 0.5804652 ],
            [0.83437836, 0.17531359],
            [0.5109179 , 0.91586626],
            [0.21497321, 0.41104853],
            [0.7946409 , 0.30716085],
            [0.3172475 , 0.15829349]]],
 
 
          [[[0.5417241 , 0.49205697],
            [0.19820452, 0.25472498],
            [0.2333138 , 0.2071842 ],
            [0.5443722 , 0.01052618],
            [0

In [15]:
hot_list = tf.constant([1,0,3,2])
tf.one_hot(hot_list,depth=7,on_value=100,off_value=50)

<tf.Tensor: shape=(4, 7), dtype=int32, numpy=
array([[ 50, 100,  50,  50,  50,  50,  50],
       [100,  50,  50,  50,  50,  50,  50],
       [ 50,  50,  50, 100,  50,  50,  50],
       [ 50,  50, 100,  50,  50,  50,  50]], dtype=int32)>

In [16]:
tf.math.square(hot_list)
tf.math.sqrt(tf.cast(hot_list,dtype=tf.float32))
tf.math.log(tf.cast(hot_list,dtype=tf.float32))

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.       ,      -inf, 1.0986123, 0.6931472], dtype=float32)>

In [20]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [19]:
!nvidia-smi


Thu Sep 18 05:26:53 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   50C    P0             27W /   70W |     106MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----